# Generated by Django 5.1.3 on 2024-11-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_name', models.CharField(max_length=100)),
                ('card_description', models.TextField()),
                ('card_category', models.CharField(max_length=50)),
                ('card_type', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('card_status', models.CharField(max_length=20)),
                ('expiration_date', models.DateField()),
                ('card_number', models.CharField(max_length=50, unique=True)),
                ('card_quantity', models.IntegerField()),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
