# Generated by Django 5.1.3 on 2024-11-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
