# Generated by Django 5.1.3 on 2024-11-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcards', '0002_giftcard_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='card_number',
            field=models.CharField(default='0000000000', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='giftcard',
            name='card_quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
