# Generated by Django 5.1.3 on 2024-11-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcards', '0005_alter_giftcard_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcard',
            name='card_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
